export const FETCHING_DATA = 'FETCHING_DATA'
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS'
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE'
export const BASE_URL  = ''
export const BASE_URL_KECAMATAN  = ''
export const BASE_URL_KTP  = ''


export const FETCHING_DATA_KECAMATAN = 'FETCHING_DATA_KECAMATAN'
export const FETCHING_DATA_KECAMATAN_SUCCESS = 'FETCHING_DATA_KECAMATAN_SUCCESS'
export const FETCHING_DATA_KECAMATAN_FAILURE = 'FETCHING_DATA_KECAMATAN_FAILURE'